apiVersion: v1
kind: Service
metadata:
  name: pedidos-service
  labels:
    app: pedidos
spec:
  selector:
    app: pedidos
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  type: LoadBalancer